### PR TITLE
Name field added in the email subscription

### PR DESCRIPTION
**Pull request by Pulkitmangla**

### CODE REVIEW

**Comment by stefek99** [comment]
Our first ever pull request... Let me check your branch and see how Mailchimp integrates with it...

**Comment by stefek99** [comment]
Thank you @Pulkitmangla - you've actually motivated me to get this sorted... Magic!

**Comment by Pulkitmangla** [comment]
@stefek99 Your welcome..  Will be trying to solve more issues..

**Comment by stefek99** [comment]
No I don't like solving merge issues - it's wasted energy... Accepted your changes and then added a few fixes on top :)

**Comment by stefek99** [comment]
@Pulkitmangla - how did you find us? We are just getting started...

Recently (past couple of days) we've been promoting these:

🚀  pre-Kickstarter social media campaign: https://www.thunderclap.it/projects/55763-astralship-kickstarter-is-live

🚀  pre-Kickstarter options: https://astralship.org/investment#ready

(we are pretty much ready)

**Comment by Pulkitmangla** [comment]
@stefek99 I was just finding issues and solving them and that's how i found you..

**Pull request merged**
